FROM python:3.11-slim

# Instala dependências do Tk e compilação
RUN apt-get update && \
    apt-get install -y python3-tk tk tcl && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "crypto_gui.py"]
